name: Production Deployment (on Push)
on:
  repository_dispatch:
    types: deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Perform deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: thenewsmaster
          heroku_email: ${{secrets.EMAIL}}
          branch: main
